Repository Eats-Finder/frontend, pull requests merged in 2024-05, with the labels that each got.

#3 [Feat] - 폴더 구조 클 생성
  src/app/join/page.tsx
  src/app/page.tsx
Labels: Feat

#7 [Feat] 디자인 시스템 등록
  tailwind.config.ts
Labels: ⭐Feat

#8 [Merge] - 디자인 시스템 등록
  tailwind.config.ts
Labels: ⭐Feat

#10 [feat/set prettierrc] - prettierrc 설치 적용
  .eslintrc.json
  .prettierrc
  .vscode/settings.json
  package-lock.json
  package.json
  src/app/globals.css
  src/app/join/page.tsx
  src/app/page.tsx
  src/app/signup/page.tsx
Labels: 📁Chore
